### ISSUE TITLE
Caches Thread Safe?

### ISSUE THREAD

**Issue by adammartin-mednax** [nathanl/caches#1]
Are caches thread safe?  I have enjoyed using the project but have a case where I want a TTL cache to span thread boundaries but don't know if it's safe.

Thanks!

**Comment by nathanl** [comment]
@adammartin-hisc Congrats on opening issue 1! :) I'm glad to know somebody is using this project.

I didn't take thread safety into account when making this. However, I think you could wrap your usage in Mutex and be safe: https://ruby-doc.org/core-2.2.0/Mutex.html

Want to test that and let me know what you find?

**Comment by nathanl** [comment]
Closing - archiving this repo. :)
